name: Capstone CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        if: steps.frontend-node-cache.outputs.cache-hit != 'true'
        run: npm install --prefix ./front-end

      - name: Cache frontend node_modules
        id: frontend-node-cache
        uses: actions/cache@v2
        with:
          path: front-end/node_modules
          key: frontend-node-modules-${{ hashFiles('front-end/package-lock.json') }}

      - name: Install backend dependencies
        if: steps.backend-node-cache.outputs.cache-hit != 'true'
        run: npm install --prefix ./back-end

      - name: Cache backend node_modules
        id: backend-node-cache
        uses: actions/cache@v2
        with:
          path: backend-end/node_modules
          key: backend-node-modules-${{ hashFiles('back-end/package-lock.json') }}

      - run: npm run build --if-present

      - name: Test frontend
        run: npm run test:frontend
        env:
          DATABASE_URL_TEST: postgresql://postgres:postgres@127.0.0.1:5432
          NODE_ENV: test

      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: |
            front-end/.screenshots

      - name: Test backend
        if: always()
        run: npm run test:backend
        env:
          DATABASE_URL_TEST: postgresql://postgres:postgres@127.0.0.1:5432
          NODE_ENV: test
